version: "3.8"

services:

  node-service:
    build: .

    container_name: portfolio_container
    tty: true
    #restart: always
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:4000:4000"
      - "0.0.0.0:5000:5000"
      - "0.0.0.0:8000:80"
    volumes:
      - .:/usr/src/app
      


  # mongo:
  #   image: mongo:4.2-bionic
  #   # restart: always
  #   container_name: mongo-container
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 1004
  #     MONGO_INITDB_DATABASE: homeServices
  #   volumes:
  #       - ./mongoDatabase:/data/db

  #   ports:
  #     - 27017:27017

  # mongo-express:
  #   image: mongo-express:0.54
  #   # restart: always
    
  #   container_name: mongo-express-container
  #   environment:
  #   ports:
  #     - 8888:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 1004
